
package my.gui;

import my.gui.Log;
//import com.mysql.jdbc.log.Log;
import java.sql.SQLException;
import java.util.*;
import java.util.ArrayList;


public class gui extends javax.swing.JFrame {

    public String usuario, password, nombrebd, columna;
    ArrayList prueba1 = new ArrayList();
    ArrayList prueba2 = new ArrayList();
    HashMap map = new HashMap();

    /** Creates new form gui */
    public gui() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        Titulo2 = new javax.swing.JLabel();
        DatoBD = new javax.swing.JLabel();
        NombreBD = new javax.swing.JTextField();
        DatoUsuario = new javax.swing.JLabel();
        UsuarioBD = new javax.swing.JTextField();
        DatoPassword = new javax.swing.JLabel();
        BotonOK = new javax.swing.JButton();
        PasswordBD = new javax.swing.JPasswordField();
        PanelGral = new javax.swing.JTabbedPane();
        PanelDatos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextoDatos = new javax.swing.JTextArea();
        PanelArbol = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextoArbol = new javax.swing.JTextArea();
        BotonGrafico = new javax.swing.JButton();
        PanelLog = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextoLog = new javax.swing.JTextArea();
        Titulo1 = new javax.swing.JLabel();
        Inform1 = new javax.swing.JLabel();
        Inform2 = new javax.swing.JLabel();
        Inform3 = new javax.swing.JLabel();
        DatoColumna = new javax.swing.JLabel();
        DatoCerteza = new javax.swing.JLabel();
        Certeza = new javax.swing.JSpinner();
        ColumnaBD = new javax.swing.JTextField();
        Discretizacion = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Algoritmo J48   -    A. Aranda (54210), F. Cardozo (51300), L. Figueredo (51160)");
        setAlwaysOnTop(true);
        setName("VentanaPrincipal"); // NOI18N

        Titulo2.setFont(new java.awt.Font("Tahoma", 1, 14));
        Titulo2.setForeground(new java.awt.Color(102, 102, 255));
        Titulo2.setText("Conexion a la Base de Datos");

        DatoBD.setText("Nombre de la Base de Datos:");

        DatoUsuario.setText("Nombre de Usuario:");

        UsuarioBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioBDActionPerformed(evt);
            }
        });

        DatoPassword.setText("Contraseña:");

        BotonOK.setText("OK");
        BotonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonOKActionPerformed(evt);
            }
        });

        PasswordBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordBDActionPerformed(evt);
            }
        });

        PanelGral.setBackground(new java.awt.Color(153, 153, 153));
        PanelGral.setAutoscrolls(true);

        TextoDatos.setColumns(20);
        TextoDatos.setEditable(false);
        TextoDatos.setRows(5);
        jScrollPane1.setViewportView(TextoDatos);

        javax.swing.GroupLayout PanelDatosLayout = new javax.swing.GroupLayout(PanelDatos);
        PanelDatos.setLayout(PanelDatosLayout);
        PanelDatosLayout.setHorizontalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelDatosLayout.setVerticalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelGral.addTab("Datos de la Tabla", PanelDatos);

        jScrollPane2.setAutoscrolls(true);

        TextoArbol.setColumns(20);
        TextoArbol.setEditable(false);
        TextoArbol.setRows(5);
        jScrollPane2.setViewportView(TextoArbol);

        BotonGrafico.setText("Ver Grafico del Arbol");

        javax.swing.GroupLayout PanelArbolLayout = new javax.swing.GroupLayout(PanelArbol);
        PanelArbol.setLayout(PanelArbolLayout);
        PanelArbolLayout.setHorizontalGroup(
            PanelArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelArbolLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                    .addComponent(BotonGrafico))
                .addContainerGap())
        );
        PanelArbolLayout.setVerticalGroup(
            PanelArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelArbolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonGrafico)
                .addContainerGap())
        );

        PanelGral.addTab("Arbol Generado", PanelArbol);

        jScrollPane3.setAutoscrolls(true);

        TextoLog.setColumns(20);
        TextoLog.setEditable(false);
        TextoLog.setRows(5);
        jScrollPane3.setViewportView(TextoLog);

        javax.swing.GroupLayout PanelLogLayout = new javax.swing.GroupLayout(PanelLog);
        PanelLog.setLayout(PanelLogLayout);
        PanelLogLayout.setHorizontalGroup(
            PanelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelLogLayout.setVerticalGroup(
            PanelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelGral.addTab("Log", PanelLog);

        Titulo1.setFont(new java.awt.Font("Tahoma", 1, 24));
        Titulo1.setForeground(new java.awt.Color(102, 102, 255));
        Titulo1.setText("Implementacion del Algoritmo J48");

        Inform1.setText("Ingrese la informacion solicitada referente a la Base de Datos y");
        Inform1.setFocusable(false);

        Inform2.setText("presione 'OK' para que la informacion obtenida de la misma sea");

        Inform3.setText("procesada. Los resultados obtenidos seran mostrados en el panel.");

        DatoColumna.setText("Columna:");

        DatoCerteza.setText("Porcentaje de Certeza:");

        Certeza.setModel(new javax.swing.SpinnerNumberModel(100, 0, 100, 1));

        ColumnaBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColumnaBDActionPerformed(evt);
            }
        });

        Discretizacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Discretizacion.setText("Tipo de Discretizacion de Datos Numericos:");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Promedio de los Valores Dados");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Valores Especificos:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(3);
        jTextArea1.setTabSize(5);
        jTextArea1.setText("columna,valor;...");
        jScrollPane4.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulo2)
                    .addComponent(Titulo1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Inform1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Inform2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Inform3)
                                    .addComponent(Discretizacion, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DatoBD, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DatoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DatoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DatoColumna, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(DatoCerteza)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                        .addComponent(Certeza, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ColumnaBD, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PasswordBD, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(UsuarioBD, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(NombreBD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                                    .addComponent(BotonOK, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton2)
                                            .addComponent(jRadioButton1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)))))
                        .addGap(40, 40, 40)
                        .addComponent(PanelGral, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(Titulo1)
                        .addGap(26, 26, 26)
                        .addComponent(Titulo2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Inform1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Inform2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Inform3)
                                .addGap(43, 43, 43)
                                .addComponent(NombreBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DatoUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UsuarioBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DatoPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PasswordBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DatoColumna)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ColumnaBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DatoCerteza)
                                    .addComponent(Certeza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(Discretizacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4)
                                .addGap(18, 18, 18)
                                .addComponent(BotonOK))
                            .addComponent(PanelGral, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(DatoBD)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        PanelGral.getAccessibleContext().setAccessibleName("Datos de la Tabla");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioBDActionPerformed


    private void BotonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonOKActionPerformed
        // TODO add your handling code here:
        usuario = UsuarioBD.getText();
        nombrebd = NombreBD.getText();
        password = PasswordBD.getText();
        columna = ColumnaBD.getText();


        //Cargar los datos de la BD para mostrar en el Panel de Datos
        TextoDatos.setText("\n  Base de Datos: ");
        TextoDatos.append(nombrebd);
        TextoDatos.append("\n  Usuario: ");
        TextoDatos.append(usuario);
        TextoDatos.append("\n\n  Información extraida de la Base de Datos: \n");
        
        DataBase datos = new DataBase();

        datos.Conectar(nombrebd,usuario, password);

        try{
            datos.getNombresColumnas();
            map = datos.ParseoDB(prueba1,prueba2);
            tree.tree(map);
            datos.getValoresPantalla();
        }
        catch(SQLException e){
            System.out.println("Error al parsear: " + e);
        }
        TextoDatos.append("      ");
        for(int i = 0; i < datos.data.size(); i++){
            TextoDatos.append(datos.data.get(i).toString());
        }
        
        //Generar el Log
        TextoLog.setText("");
        Log log = new Log();
        for(int i = 0; i < log.datosLog.size(); i++){
            TextoLog.append(log.datosLog.get(i).toString());
        }

        //GraficoArbol arbol = new GraficoArbol();
        //arbol.setVisible(true);
        
       // JOptionPane.showMessageDialog(jFrame1, password);
        datos.Desconectar();
        TextoLog.append("  " + new Date() + "\t   Termino de la Ejecucion\n");
    }//GEN-LAST:event_BotonOKActionPerformed

    /*private void BotonGraficoActionPerformed(java.awt.event.ActionEvent evt) {
        GraficoArbol arbol = new GraficoArbol();
        arbol.setVisible(true);
    }*/
    private void PasswordBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordBDActionPerformed

    private void ColumnaBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColumnaBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColumnaBDActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonGrafico;
    private javax.swing.JButton BotonOK;
    private javax.swing.JSpinner Certeza;
    private javax.swing.JTextField ColumnaBD;
    private javax.swing.JLabel DatoBD;
    private javax.swing.JLabel DatoCerteza;
    private javax.swing.JLabel DatoColumna;
    private javax.swing.JLabel DatoPassword;
    private javax.swing.JLabel DatoUsuario;
    private javax.swing.JLabel Discretizacion;
    private javax.swing.JLabel Inform1;
    private javax.swing.JLabel Inform2;
    private javax.swing.JLabel Inform3;
    private javax.swing.JTextField NombreBD;
    private javax.swing.JPanel PanelArbol;
    private javax.swing.JPanel PanelDatos;
    private javax.swing.JTabbedPane PanelGral;
    private javax.swing.JPanel PanelLog;
    private javax.swing.JPasswordField PasswordBD;
    private javax.swing.JTextArea TextoArbol;
    private javax.swing.JTextArea TextoDatos;
    private javax.swing.JTextArea TextoLog;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JTextField UsuarioBD;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    
}
