
package my.gui;
//import weka.gui.treevisualizer.*;

//import com.mysql.jdbc.log.Log;
import java.sql.SQLException;


public class gui extends javax.swing.JFrame {

    public String usuario, password, nombrebd;

    /** Creates new form gui */
    public gui() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        Titulo2 = new javax.swing.JLabel();
        DatoBD = new javax.swing.JLabel();
        NombreBD = new javax.swing.JTextField();
        DatoUsuario = new javax.swing.JLabel();
        UsuarioBD = new javax.swing.JTextField();
        DatoPassword = new javax.swing.JLabel();
        BotonOK = new javax.swing.JButton();
        PasswordBD = new javax.swing.JPasswordField();
        PanelGral = new javax.swing.JTabbedPane();
        PanelDatos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextoDatos = new javax.swing.JTextArea();
        PanelArbol = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextoArbol = new javax.swing.JTextArea();
        PanelLog = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextoLog = new javax.swing.JTextArea();
        Titulo1 = new javax.swing.JLabel();
        Inform1 = new javax.swing.JLabel();
        Inform2 = new javax.swing.JLabel();
        Inform3 = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Algoritmo J48   -    A. Aranda (54210), F. Cardozo (51300), L. Figueredo (51160)");
        setName("VentanaPrincipal"); // NOI18N

        Titulo2.setFont(new java.awt.Font("Tahoma", 1, 14));
        Titulo2.setText("Conexion a la Base de Datos");

        DatoBD.setText("Nombre de la Base de Datos:");

        DatoUsuario.setText("Nombre de Usuario:");

        UsuarioBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioBDActionPerformed(evt);
            }
        });

        DatoPassword.setText("Contraseña:");

        BotonOK.setText("OK");
        BotonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonOKActionPerformed(evt);
            }
        });

        PasswordBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordBDActionPerformed(evt);
            }
        });

        PanelGral.setBackground(new java.awt.Color(153, 153, 153));
        PanelGral.setAutoscrolls(true);

        TextoDatos.setColumns(20);
        TextoDatos.setEditable(false);
        TextoDatos.setRows(5);
        jScrollPane1.setViewportView(TextoDatos);

        javax.swing.GroupLayout PanelDatosLayout = new javax.swing.GroupLayout(PanelDatos);
        PanelDatos.setLayout(PanelDatosLayout);
        PanelDatosLayout.setHorizontalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelDatosLayout.setVerticalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelGral.addTab("Datos de la Tabla", PanelDatos);

        jScrollPane2.setAutoscrolls(true);

        TextoArbol.setColumns(20);
        TextoArbol.setEditable(false);
        TextoArbol.setRows(5);
        jScrollPane2.setViewportView(TextoArbol);

        javax.swing.GroupLayout PanelArbolLayout = new javax.swing.GroupLayout(PanelArbol);
        PanelArbol.setLayout(PanelArbolLayout);
        PanelArbolLayout.setHorizontalGroup(
            PanelArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelArbolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelArbolLayout.setVerticalGroup(
            PanelArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelArbolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelGral.addTab("Arbol Generado", PanelArbol);

        jScrollPane3.setAutoscrolls(true);

        TextoLog.setColumns(20);
        TextoLog.setEditable(false);
        TextoLog.setRows(5);
        jScrollPane3.setViewportView(TextoLog);

        javax.swing.GroupLayout PanelLogLayout = new javax.swing.GroupLayout(PanelLog);
        PanelLog.setLayout(PanelLogLayout);
        PanelLogLayout.setHorizontalGroup(
            PanelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelLogLayout.setVerticalGroup(
            PanelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelGral.addTab("Log", PanelLog);

        Titulo1.setFont(new java.awt.Font("Tahoma", 1, 24));
        Titulo1.setText("Implementacion del Algoritmo J48");

        Inform1.setText("Ingrese la informacion solicitada referente a la Base de Datos y");
        Inform1.setFocusable(false);

        Inform2.setText("presione 'OK' para que la informacion obtenida de la misma sea");

        Inform3.setText("procesada. Los resultados obtenidos seran mostrados en el panel.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Titulo2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Inform2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Inform1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Inform3, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(UsuarioBD)
                                    .addComponent(NombreBD, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                    .addComponent(PasswordBD)
                                    .addComponent(BotonOK, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(DatoBD, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DatoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DatoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(40, 40, 40)
                        .addComponent(PanelGral, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Titulo1))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Titulo1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Titulo2)
                        .addGap(18, 18, 18)
                        .addComponent(Inform1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Inform2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Inform3)
                        .addGap(35, 35, 35)
                        .addComponent(DatoBD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NombreBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(DatoUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UsuarioBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(DatoPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PasswordBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonOK))
                    .addComponent(PanelGral, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        PanelGral.getAccessibleContext().setAccessibleName("Datos de la Tabla");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioBDActionPerformed


    private void BotonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonOKActionPerformed
        // TODO add your handling code here:
        usuario = UsuarioBD.getText();
        nombrebd = NombreBD.getText();
        password = PasswordBD.getText();


        //Cargar los datos de la BD para mostrar en el Panel de Datos
        TextoDatos.setText("\n  Base de Datos: ");
        TextoDatos.append(nombrebd);
        TextoDatos.append("\n  Usuario: ");
        TextoDatos.append(usuario);
        TextoDatos.append("\n\n  Información extraida de la Base de Datos: \n");
        
        DataBase datos = new DataBase();

        datos.Conectar();
        try{
            datos.ParseoDB();
        }
        catch(SQLException e){
            System.out.println("Error al parsear");
        }
        TextoDatos.append("      ");
        for(int i = 0; i < datos.data.size(); i++){
            TextoDatos.append(datos.data.get(i).toString());
        }
        
        //Generar el Log
        /*TextoLog.setText("");
        Log log=new Log();
        for(int i = 0; i < log.datosLog.size(); i++){
            TextoLog.append(log.datosLog.get(i).toString());
        }*/
                
        GraficoArbol arbol = new GraficoArbol();
        arbol.setVisible(true);

        
       // JOptionPane.showMessageDialog(jFrame1, password);
        datos.Desconectar();
    }//GEN-LAST:event_BotonOKActionPerformed

    private void PasswordBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordBDActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonOK;
    private javax.swing.JLabel DatoBD;
    private javax.swing.JLabel DatoPassword;
    private javax.swing.JLabel DatoUsuario;
    private javax.swing.JLabel Inform1;
    private javax.swing.JLabel Inform2;
    private javax.swing.JLabel Inform3;
    private javax.swing.JTextField NombreBD;
    private javax.swing.JPanel PanelArbol;
    private javax.swing.JPanel PanelDatos;
    private javax.swing.JTabbedPane PanelGral;
    private javax.swing.JPanel PanelLog;
    private javax.swing.JPasswordField PasswordBD;
    private javax.swing.JTextArea TextoArbol;
    private javax.swing.JTextArea TextoDatos;
    private javax.swing.JTextArea TextoLog;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JTextField UsuarioBD;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    
}
